/* Adapted from trip-map-builder: DAYS, overview/day views and Leaflet map engine.
 * Geographic markers are representative WGS84 positions, not verified entrances.
 * Navigation uses POI-name search, never approximate coordinates. */
'use strict';
const HOTEL={name:'全季酒店（乌鲁木齐友好店）',lat:43.824,lng:87.592,query:'全季酒店 乌鲁木齐友好店 克拉玛依东街84号',note:'酒店已由用户选定；当前坐标仍为友好商圈区域示意，不是酒店精确位置。请按店名搜索，并用订单核对克拉玛依东街84号。'};
const POIS={
 city:HOTEL,
 tianchi:{name:'天山天池',lat:43.886028,lng:88.132389,query:'天山天池游客中心',note:'主湖参考位置，不是游客中心或停车场'},
 jiang:{name:'江布拉克',lat:43.567,lng:89.753,query:'江布拉克景区游客中心',note:'景区区域参考位置，不是驾车入口'},
 park:{name:'水磨沟公园',lat:43.836,lng:87.648,query:'乌鲁木齐 水磨沟公园',note:'公园区域示意，入口请在导航中确认'},
 museum:{name:'新疆博物馆',lat:43.8183,lng:87.5812,query:'新疆维吾尔自治区博物馆 西北路581号',note:'馆区参考位置，参观入口以预约信息为准'}
};
const DAYS=[
 {id:0,label:'全程总览',color:'#1d5648'},
 {id:1,label:'D1 天山天池',title:'天山天池一日游',color:'#2d6d9b',summary:'高山湖泊 · 雪山云杉',hours:'07:30 — 18:00',route:'乌鲁木齐 → 天山天池 → 乌鲁木齐',points:['city','tianchi'],tags:['当日往返','湖边栈道','自带简餐'],cost:'原攻略：155元/人（含区间车）',warning:'票价未实时核验。地图主湖标记不是驾车终点，请导航到游客中心，再乘区间车。',stops:[
 ['07:30','从全季友好店出发','住宿已选：全季酒店（乌鲁木齐友好店）。',HOTEL.query],
 ['09:30','天池游客中心','抵达后换乘区间车。原攻略建议坐右侧靠窗。','天山天池游客中心'],
 ['10:00—15:30','湖泊、栈道与森林步道','游客中心 → 区间车 → 天池主湖 → 湖边栈道 → 定海神针 → 森林步道 → 返回。','', '区间车及景区步道以当天开放情况为准；景区内餐饮较贵，可自带零食和水，在允许区域简餐。'],
 ['16:00','离开景区','结束游览，返回市区。'],['18:00左右','回到全季友好店','晚餐后返回全季酒店（乌鲁木齐友好店）休息。',HOTEL.query]],
 scheme:['乌鲁木齐出发','天池游客中心','天池主湖 · 湖边栈道','定海神针 · 森林步道','返回乌鲁木齐']},
 {id:2,label:'D2 南山沙沟',title:'南山沙沟徒步',color:'#507940',summary:'草甸溪流 · 云杉牧场',hours:'08:00 — 18:00',route:'乌鲁木齐 → 南山沙沟 → 乌鲁木齐',points:['city'],tags:['约8—10 km','徒步4—5小时','自带路餐'],warning:'原攻略未给徒步入口或轨迹。沙沟不设置推测坐标，也不生成山路导航；出发前向当地确认开放情况、停车点和合法可通行线路。',stops:[
 ['08:00','从全季友好店出发','检查天气、线路开放情况与随身装备。',HOTEL.query],['09:00—09:30','抵达南山沙沟附近','确认徒步入口，热身、整理装备。入口待确认。'],['09:30—12:00','第一段徒步','欣赏草甸、溪流、云杉林、山谷和牛羊牧场。'],['12:00—13:00','路餐与休息','自带馕、牛肉干、能量棒、香蕉、坚果、巧克力与饮水。'],['13:00—15:30','继续走 + 返回','按体力与天气调整，预留原路折返时间；没有可靠轨迹时不进入不明支路。'],['16:00左右','回到车辆','清点随身物品，带走垃圾。'],['17:00—18:00','返回全季友好店','回到全季酒店（乌鲁木齐友好店）休息。',HOTEL.query]],equipment:'防滑徒步鞋、登山杖、冲锋衣/防风衣、帽子、墨镜、SPF50+防晒、1.5—2L水/人、充电宝。饮水量按天气和个人情况调整。',scheme:['全季友好店出发','沙沟入口 · 待确认','草甸 · 溪流 · 云杉林','路餐后折返','回到车辆 → 返回酒店']},
 {id:3,label:'D3 江布拉克',title:'江布拉克自驾游',color:'#be662b',summary:'草原麦田 · 自驾风景',hours:'07:00 — 20:30',route:'乌鲁木齐 → 江布拉克 → 乌鲁木齐',points:['city','jiang'],tags:['全天自驾','车程较长','建议早出发'],cost:'原攻略：门票55元/人 + 自驾车票100元/辆',warning:'票价及自驾入园规则未实时核验。今天车程较长，安排轮换驾驶或充分休息；游览顺序以景区道路指引为准。',stops:[
 ['07:00','从全季友好店出发','早点出发，预留当天往返的驾驶时间。',HOTEL.query],['10:00左右','抵达江布拉克','在游客中心核对购票、自驾入园和道路开放信息。','江布拉克景区游客中心'],['10:00—16:00','景区自驾与观景','游客中心 → 天山麦海（5号观景台）→ 天山怪坡 → 花海子 → 江布拉克大峡谷 → 断桥。','', '保留原攻略游览次序；内部节点没有已核验坐标，仅展示顺序，不伪造自驾道路轨迹。'],['16:00—16:30','离开景区','根据体力、光照和路况开始返程。'],['19:30—20:30','回到全季友好店','抵达时间沿用原攻略估计，以实际路况为准。',HOTEL.query]],scheme:['游客中心','天山麦海 · 5号观景台','天山怪坡','花海子','江布拉克大峡谷','断桥 → 返回全季友好店']},
 {id:4,label:'D4 自由活动',title:'给城市留一天空白',color:'#785293',summary:'商圈 · 咖啡 · 散步 · 放松',hours:'不设固定时间',route:'乌鲁木齐市区自由活动',points:['city','park'],tags:['全部可选','不用赶路','仍住原酒店'],warning:'以下是原攻略提供的选项，不要求全部打卡。地图仅标友好商圈与水磨沟公园，未擅自添加店铺或餐厅。',stops:[
 ['自然醒','慢慢吃早餐','根据状态决定今天出不出门。'],['可选 · 散步','水磨沟公园','轻松散步；如果累了，可直接留在商圈或酒店休息。','乌鲁木齐 水磨沟公园'],['可选 · 购物','友好商圈 / 大型商场','逛街，购买干果、奶制品等伴手礼。','乌鲁木齐 友好商圈'],['可选 · 餐饮','咖啡与新疆特色餐厅','随走随选，不固定店铺。'],['可选 · 放松','SPA / 按摩 / 酒店休息','今天以恢复体力为主。'],['晚餐后','回全季友好店休息','整理行李，为明天参观与返程做准备。',HOTEL.query]],scheme:['睡到自然醒','水磨沟公园 · 可选','友好商圈 · 可选','咖啡 / 美食 / 放松','返回全季友好店休息']},
 {id:5,label:'D5 博物馆·返程',title:'新疆博物馆，轻松收尾',color:'#3b7294',summary:'历史文化 · 午餐 · 下午返程',hours:'10:30参观 · 下午返程',route:'新疆博物馆 → 午餐 → 酒店取行李 → 还车 → 机场',points:['museum','city'],tags:['半天参观','提前预约','航班待补充'],warning:'未提供出行日期、航班或航站楼。无法核对是否遇休馆日，也无法确认下午返程衔接；如航班较早，应缩短或调整参观。',stops:[
 ['10:30—13:00','新疆博物馆','从全季友好店出发，按预约时段参观。地址：乌鲁木齐市西北路581号。','新疆维吾尔自治区博物馆 西北路581号','原攻略记载：周二至周日10:30—19:00，18:00停止入馆，可提前一周免费预约。以上不是实时确认信息，出行前以馆方公告和预约页面为准；如D5休馆，可考虑与D4对调。'],['13:00—14:00','午餐','在参观结束后就近用餐。'],['午餐后','全季友好店取行李','回全季酒店（乌鲁木齐友好店）取行李，再前往约定还车点。',HOTEL.query],['按航班倒推','还车 → 前往机场','还车地点与机场航站楼待确认。以机票及租车订单为准，预留交通、还车、值机和安检时间。']],scheme:['新疆博物馆','午餐','全季友好店取行李','还车 · 地点待确认','机场返程 · 航班待确认']}
];
let cur=0,mode='schematic',map=null,layer=null,leafletPromise=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function navLinks(query){if(!query)return '';const q=encodeURIComponent(query);return `<div class="links"><a href="https://uri.amap.com/search?keyword=${q}&city=%E4%B9%8C%E9%B2%81%E6%9C%A8%E9%BD%90&src=tripmap&callnative=1" target="_blank" rel="noopener noreferrer">高德搜索 ↗</a><a href="https://maps.apple.com/?q=${q}" target="_blank" rel="noopener noreferrer">Apple 地图 ↗</a></div>`;}
function overviewContent(){return `<span class="eyebrow">URUMQI · 4.5 DAYS</span><h2>住在城里，走进山野</h2><p class="intro">三天向山里出发，一天留给城市，最后半天走进博物馆。</p><div class="stats"><div class="stat"><strong>4 晚</strong><span>全季酒店 · 乌鲁木齐友好店</span></div><div class="stat"><strong>3 次</strong><span>郊外当日往返</span></div></div><div>${DAYS.slice(1).map(d=>`<button class="day-card" data-day="${d.id}" style="--day-color:${d.color}"><span class="day-number">D${d.id}</span><span><strong>${d.title}</strong><small>${d.summary}</small></span><span aria-hidden="true">›</span></button>`).join('')}</div><div class="note"><strong>已选：${HOTEL.name}</strong><br>4晚同住；每日出发、回住和D5取行李都以这家酒店为基点。导航使用完整店名，请用订单核对门店地址。地图暂显示友好商圈参考位置。${navLinks(HOTEL.query)}</div><div class="note warn"><strong>出发前还需确认</strong><br>日期与航班、沙沟入口及轨迹、票价和预约。所有时间沿用原攻略，统一按北京时间（UTC+8）显示。</div><button class="art-thumb" data-art><img src="route-plan.jpg" alt="上传的手绘路线图缩略图"><span>打开原始手绘路线图 ↗</span></button>${sourceBlock()}`;}
function sourceBlock(){return `<details class="source"><summary>内容来源与地图说明</summary><p>行程、时间、装备、票价参考：上传的《乌鲁木齐Citywalk.md》及手绘路线规划图。未添加新景点或店铺。</p><p>票价、开放与预约信息尚未完成官方实时核验。行程不包含实时路况、天气或户外轨迹。</p><p>地理点位仅供查看相对位置；不将湖心、景区示意点、住宿商圈用于逐点驾驶导航。沙沟入口及机场航站楼未确认，不在地理图虚构落点。</p><p><a href="https://en.wikipedia.org/wiki/Heavenly_Lake_of_Tian_Shan" target="_blank" rel="noopener noreferrer">天池位置参考</a> · <a href="https://wlt.xinjiang.gov.cn/wlt/c112782/202208/485879adec234d0c948ec6ae14d89618.shtml" target="_blank" rel="noopener noreferrer">江布拉克景区介绍</a> · <a href="https://www.silkroadtravel.com/urumqi/attraction/xinjiang-regional-museum" target="_blank" rel="noopener noreferrer">博物馆地址参考</a></p></details>`;}
function locCard(s,i){return `<article class="stop"><div class="time">${esc(s[0])}</div><h3>${esc(s[1])}</h3><p>${esc(s[2])}</p>${navLinks(s[3])}${s[4]?`<details class="detail"><summary>查看详细提醒</summary><p>${esc(s[4])}</p></details>`:''}</article>`;}
function renderDay(id){const d=DAYS[id];return `<span class="eyebrow">DAY ${id} / 05</span><h2>${d.title}</h2><p class="intro">${d.route}</p><div>${d.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div>${d.cost?`<div class="note">${d.cost}<br><small>仅作原攻略预算参考，以购票时公布为准。</small></div>`:''}<div class="timeline">${d.stops.map(locCard).join('')}</div>${d.equipment?`<div class="note"><strong>徒步装备</strong><br>${d.equipment}</div>`:''}<div class="note warn">${d.warning}</div>${sourceBlock()}`;}
function svgNode(x,y,w,title,sub,color,id){return `<g role="button" tabindex="0" data-day="${id}" aria-label="查看${esc(title)}"><rect x="${x}" y="${y}" width="${w}" height="83" rx="12" fill="white" stroke="${color}" stroke-width="1.3"/><rect x="${x+12}" y="${y+14}" width="34" height="24" rx="6" fill="${color}"/><text x="${x+29}" y="${y+31}" fill="white" text-anchor="middle" font-size="13" font-weight="700">D${id}</text><text x="${x+12}" y="${y+61}" fill="#183b34" font-size="18" font-weight="600">${title}</text><text x="${x+53}" y="${y+30}" fill="#52665e" font-size="12">${sub}</text></g>`;}
function renderDiagram(){const small=window.matchMedia('(max-width:700px)').matches;let s='';
 if(cur===0){const w=small?440:800,h=small?460:600;const nodes=small?[[18,24,192,'天山天池','湖泊 · 云杉',1],[230,24,192,'南山沙沟','轻徒步 · 入口待定',2],[18,332,192,'江布拉克','草原 · 麦田',3],[230,332,192,'市区自由活动','咖啡 · 散步',4]]:[[48,42,240,'天山天池','高山湖泊 · 云杉',1],[512,42,240,'南山沙沟','溪流草甸 · 入口待定',2],[48,426,240,'江布拉克','草原麦田 · 自驾',3],[512,426,240,'市区自由活动','商圈咖啡 · 休闲',4]];const cx=w/2,cy=small?210:265;
 s=`<svg viewBox="0 0 ${w} ${h}" aria-label="乌鲁木齐为中心的五天行程关系图，非按地理比例绘制"><text x="${w-22}" y="${h-14}" text-anchor="end" fill="#647568" font-size="12">路线关系示意 · 非地理方位</text>`;
 nodes.forEach(n=>{const col=DAYS[n[5]].color;const ny=n[1]<cy?n[1]+83:n[1];s+=`<path d="M${cx},${cy} Q${n[0]+n[2]/2},${cy} ${n[0]+n[2]/2},${ny}" fill="none" stroke="${col}" stroke-width="2" stroke-dasharray="6 6" opacity=".7"/>`;});
 s+=`<rect x="${cx-105}" y="${cy-37}" width="210" height="74" rx="15" fill="#1d5648"/><text x="${cx}" y="${cy-5}" text-anchor="middle" fill="white" font-size="25" font-weight="700">乌鲁木齐</text><text x="${cx}" y="${cy+19}" text-anchor="middle" fill="#e4f0e5" font-size="13">全季友好店 · 4晚同住</text>`;
 nodes.forEach(n=>s+=svgNode(...n.slice(0,5),DAYS[n[5]].color,n[5]));
 const by=small?260:344;s+=`<g role="button" tabindex="0" data-day="5" aria-label="查看D5新疆博物馆和返程"><rect x="${cx-121}" y="${by}" width="242" height="47" rx="10" fill="#ebf2f7" stroke="#3b7294"/><text x="${cx}" y="${by+29}" fill="#315b77" text-anchor="middle" font-size="16" font-weight="600">D5 新疆博物馆 → 返程</text></g></svg>`;
 }else{const d=DAYS[cur],h=Math.max(440,d.scheme.length*64+60),w=small?440:650;const gap=64,start=50;
 s=`<svg viewBox="0 0 ${w} ${h}" aria-label="${esc(d.title)}顺序示意"><text x="30" y="26" fill="#66776b" font-size="12">${cur===4?'以下项目均为可选，不需按顺序完成':'顺序示意 · 不代表真实道路或徒步轨迹'}</text>`;
 d.scheme.forEach((name,i)=>{const y=start+i*gap;if(i<d.scheme.length-1&&cur!==4)s+=`<path d="M61,${y+37} L61,${y+gap}" stroke="${d.color}" stroke-width="2" stroke-dasharray="4 5"/><path d="M57,${y+gap-8} L61,${y+gap-3} L65,${y+gap-8}" fill="none" stroke="${d.color}"/>`;s+=`<rect x="34" y="${y}" width="${w-68}" height="48" rx="9" fill="#fff" stroke="#d5e1d8"/><circle cx="61" cy="${y+24}" r="13" fill="${d.color}"/><text x="61" y="${y+29}" text-anchor="middle" font-size="13" fill="white">${i+1}</text><text x="86" y="${y+30}" font-size="18" fill="#183b34">${name}</text>`;});s+='</svg>';
 }$('diagram').innerHTML=s;}
function go(id){if(!DAYS[id])return;cur=id;const d=DAYS[id];document.documentElement.style.setProperty('--accent',d.color);$('tabs').querySelectorAll('button').forEach(t=>t.setAttribute('aria-current',+t.dataset.day===id?'page':'false'));$('content').innerHTML=id?renderDay(id):overviewContent();$('content').scrollTop=0;$('map-kicker').textContent=id?'DAY '+id+' · '+d.hours:'TRIP OVERVIEW';$('map-title').textContent=id?d.title:'以乌鲁木齐为起点';renderDiagram();if(mode==='geo')showDay(id);}
function message(text){$('map-message').textContent=text;$('map-message').hidden=!text;}
function loadLeaflet(){if(window.L)return Promise.resolve();if(leafletPromise)return leafletPromise;leafletPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';const timeout=setTimeout(()=>reject(new Error('timeout')),15000);script.onload=()=>{clearTimeout(timeout);window.L?resolve():reject(new Error('missing'))};script.onerror=()=>{clearTimeout(timeout);reject(new Error('network'))};document.head.append(script);});return leafletPromise;}
async function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode?'true':'false'));$('diagram').hidden=mode==='geo';$('map').hidden=mode!=='geo';message('');$('map-caption').textContent=mode==='geo'?'虚线为目的地连线，不是实际驾车路线':'点选目的地查看当天行程 · 连线不代表真实道路';if(mode!=='geo')return;message('正在加载地理地图…');try{await loadLeaflet();if(mode!=='geo')return;if(!map){map=L.map('map',{center:[HOTEL.lat,HOTEL.lng],zoom:9,zoomControl:false});L.control.zoom({position:'topright'}).addTo(map);let errors=0;const tile=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>'}).addTo(map);tile.on('tileerror',()=>{if(++errors>3&&mode==='geo')message('地图底图暂不可用。标记仍为区域参考；可切换“路线示意”或使用地点名称搜索导航。');});layer=L.layerGroup().addTo(map);}map.invalidateSize();showDay(cur);}catch(e){if(mode==='geo'){setMode('schematic');message('地理地图暂时无法加载，已保留可交互路线示意。可使用当天详情里的地图搜索入口。');}}}
function showDay(id){if(!map)return;layer.clearLayers();const ids=id?DAYS[id].points:['city','tianchi','jiang','park','museum'];const color=DAYS[id].color;ids.forEach((key,i)=>{const p=POIS[key];const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'',html:`<div class="map-marker" style="background:${key==='city'?'#1d5648':color}">${key==='city'?'宿':i+1}</div>`,iconSize:[36,36],iconAnchor:[18,18]})}).addTo(layer);marker.bindTooltip(p.name,{direction:'top',offset:[0,-15]}).bindPopup(`<b>${p.name}</b><br>${p.note}${navLinks(p.query)}`);});if((id===1||id===3)&&ids.length>1)L.polyline(ids.map(k=>[POIS[k].lat,POIS[k].lng]),{color,weight:3,opacity:.65,dashArray:'7 8'}).addTo(layer);if(!id){[1,3].forEach(n=>L.polyline(DAYS[n].points.map(k=>[POIS[k].lat,POIS[k].lng]),{color:DAYS[n].color,weight:2.5,dashArray:'7 8',opacity:.65}).addTo(layer));}const pts=ids.map(k=>[POIS[k].lat,POIS[k].lng]);map.fitBounds(pts,{padding:[48,48],maxZoom:id===2?10:13});message(id===2?'沙沟入口未确认，未在地理图落点。请切换“路线示意”查看当天徒步安排。':id===5?'机场航站楼与还车地点待确认，暂不标注机场路线。':id===4?'D4的地点为可选项，不生成强制游览连线。':'地理位置仅作参考；点开标记后按地点名称搜索并确认实际入口。');}
function openArt(){$('art-dialog').showModal();}
$('tabs').innerHTML=DAYS.map(d=>`<button class="tab" data-day="${d.id}" style="--day-color:${d.color}" aria-current="${d.id===0?'page':'false'}">${d.label}</button>`).join('');
document.addEventListener('click',e=>{const t=e.target.closest('[data-day]');if(t)go(Number(t.dataset.day));const v=e.target.closest('[data-mode]');if(v)setMode(v.dataset.mode);if(e.target.closest('[data-art]'))openArt();});
$('diagram').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-day]')){e.preventDefault();go(Number(e.target.dataset.day));}});
$('open-art').addEventListener('click',openArt);$('close-art').addEventListener('click',()=>$('art-dialog').close());$('art-dialog').addEventListener('click',e=>{if(e.target===$('art-dialog'))$('art-dialog').close();});$('reset-map').addEventListener('click',()=>go(0));
window.addEventListener('resize',()=>{renderDiagram();if(map&&mode==='geo')map.invalidateSize();});
go(0);
